# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetupengine', '0002_auto_20160723_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='meetupengine.Course'),
        ),
    ]
