# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetupengine', '0003_auto_20160724_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='meetupengine.Classroom'),
        ),
    ]
