# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetupengine', '0005_auto_20160724_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='default_name', max_length=40),
        ),
    ]
