# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetupengine', '0006_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='registered',
            field=models.IntegerField(default=0),
        ),
    ]
